[workspace]
members = ["raytracer", "examples/*"]
resolver = "2"

[profile.release]
strip = "symbols"
codegen-units = 1
lto = "fat"

[profile.dev.package."*"]
opt-level = 3
strip = false
debug = true
codegen-units = 1

[profile.benchmarking]
inherits = "release"
strip = false
debug = true

[workspace.dependencies]
linalg = { path = "../linalg/", features=["random", "geometry", "hadamard", "physics"] }

